// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhpz8wEzTR1HWRB6XcmoUnUWPRBkc668Y',
    appId: '1:59634625636:android:a9a0fc54056b7f698d4371',
    messagingSenderId: '59634625636',
    projectId: 'gamenutrition-e2003',
    storageBucket: 'gamenutrition-e2003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChnY2bW-rTtVrhOP9jaWx4KIfzKppFzpU',
    appId: '1:59634625636:ios:ceeae519abfae00b8d4371',
    messagingSenderId: '59634625636',
    projectId: 'gamenutrition-e2003',
    storageBucket: 'gamenutrition-e2003.firebasestorage.app',
    iosBundleId: 'com.example.nutritionGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChnY2bW-rTtVrhOP9jaWx4KIfzKppFzpU',
    appId: '1:59634625636:ios:ceeae519abfae00b8d4371',
    messagingSenderId: '59634625636',
    projectId: 'gamenutrition-e2003',
    storageBucket: 'gamenutrition-e2003.firebasestorage.app',
    iosBundleId: 'com.example.nutritionGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB89fpIvAbb1mk7DVukrugNCnGlN_bl9ck',
    appId: '1:59634625636:web:ca11114b780374168d4371',
    messagingSenderId: '59634625636',
    projectId: 'gamenutrition-e2003',
    authDomain: 'gamenutrition-e2003.firebaseapp.com',
    storageBucket: 'gamenutrition-e2003.firebasestorage.app',
    measurementId: 'G-KG7KQ020VE',
  );
}
